name = "JulepLML"
uuid = "7d388285-cef2-4328-8fd5-9766fe5f706d"
authors = ["Roger-luo<rogerluo.rl18@gmail.com>"]
version = "0.1.0"

[deps]
Faker = "0efc519c-db33-5916-ab87-703215c3906f"

[compat]
julia = "1.8"
